### PR TITLE
Mobile to WebView is fixed

### PR DESCRIPTION
**Pull request by adem-emre**
I wrapped the Row in the largeWidget with a container. I imported the height and padding values of the AnimatedContainer into this container.

Fixes https://github.com/flutterturkey/festival_flutterturkiye_org/issues/113

### CODE REVIEW

**Review by bgoktugozdemir — CHANGES_REQUESTED** [review]
Hi Adem,

First of all, thank you for your contribution.

The `AnimatedContainer` helps to create the background animation. If you remove this, we cannot show the animation to the users. Can you fix it in a different way?

**Comment by adem-emre** [comment]
mobile_to_web_view

**Review by bgoktugozdemir — APPROVED** [review]
Look goods to me! Thank you for your contribution Adem.

**Comment by bgoktugozdemir** [comment]
Fixes #113

**Comment by bgoktugozdemir** [comment]
It seems, there is a format error on the code. Can you try to run this code and then push a commit.

```bash
flutter format .
```

**Comment by adem-emre** [comment]
Fixes #113

**Pull request merged**
