### PR TITLE
AppBar onTap is fixed

### LINKED ISSUE #112: AppBar onTap is not working
AppBar buttons do not navigate to the sections.

### PR DESCRIPTION
**Pull request by furkay**
Fix #112 
I added the _scrollToSection method to the onTap function of the App
bar buttons. That's how I got it to scroll to the section. The reason I put it directly in on tap is because there may be different logics in onTap. 
fix#112

### CODE REVIEW

**Comment by bgoktugozdemir** [comment]
Hi Furkay,

First of all, thank you for your contribution.

Can you add a video or gif to show us it fixes this issue?

**Review by bgoktugozdemir — COMMENTED** [review]
Hi Furkay,

First of all, thank you for your contribution.

Can you add a video or gif to show us it fixes this issue?

**Comment by furkay** [comment]
> Hi Furkay,
> 
> First of all, thank you for your contribution.
> 
> Can you add a video or gif to show us it fixes this issue?

I added it, you can check it.

**Review by bgoktugozdemir — CHANGES_REQUESTED** [review]
As far as I see, you worked on the old version of the project here. Can you try to merge your project from the main code? There should be one more button on the AppBar.

**Review by bgoktugozdemir — APPROVED** [review]
Thanks for the great work and the contribution.

**Comment by bgoktugozdemir** [comment]
Can you contact me on Twitter?

**Comment by furkay** [comment]
> Can you contact me on Twitter?

Okey sure, check dm.

**Pull request merged**
